const { withDangerousMod } = require('@expo/config-plugins');
const fs = require('fs');
const path = require('path');

/**
 * react-native-maps v1.27+ no longer ships a separate
 * `react-native-google-maps` podspec. Google Maps support is now a
 * *subspec* of the main react-native-maps pod (`react-native-maps/Google`).
 *
 * Expo's built-in withMaps config plugin still injects
 *   pod 'react-native-google-maps', path: File.dirname(... require.resolve('react-native-maps/package.json') ...)
 * into the Podfile whenever `ios.config.googleMapsApiKey` is set. This
 * causes EAS iOS builds to fail with:
 *   [!] No podspec found for `react-native-google-maps`
 *       in `/Users/expo/workingdir/build/node_modules/react-native-maps`
 *
 * Rather than patching the Podfile (which is fragile because mod order
 * isn't guaranteed), this plugin drops a *stub* podspec at the expected
 * path. The stub just depends on `react-native-maps/Google`, so CocoaPods
 * resolves the injected line cleanly and the Google subspec is what
 * actually gets compiled.
 *
 * The stub is written into node_modules/react-native-maps so it is
 * available during `pod install`, on both local prebuilds and fresh
 * EAS checkouts (EAS runs `npm install` then our prebuild mods before
 * pod install).
 */
module.exports = function withGoogleMapsSubspec(config) {
  return withDangerousMod(config, [
    'ios',
    async (config) => {
      try {
        const rnMapsDir = path.join(
          config.modRequest.projectRoot,
          'node_modules',
          'react-native-maps'
        );
        if (!fs.existsSync(rnMapsDir)) return config;

        const stubPodspecPath = path.join(
          rnMapsDir,
          'react-native-google-maps.podspec'
        );

        const stub = `# Auto-generated by plugins/withGoogleMapsSubspec.js
# react-native-maps >=1.27 removed the standalone react-native-google-maps
# podspec, but Expo's withMaps plugin still references it. This stub
# forwards to the react-native-maps/Google subspec so the injected
# Podfile line resolves cleanly.
require 'json'
package = JSON.parse(File.read(File.join(__dir__, 'package.json')))

Pod::Spec.new do |s|
  s.name         = 'react-native-google-maps'
  s.version      = package['version']
  s.summary      = 'Shim for react-native-maps Google subspec.'
  s.homepage     = package['homepage']
  s.license      = package['license']
  s.authors      = package['author']
  s.platform     = :ios, '16.0'
  s.source       = { :path => '.' }
  s.dependency 'react-native-maps/Google'
end
`;

        fs.writeFileSync(stubPodspecPath, stub, 'utf8');
        console.log(
          '[withGoogleMapsSubspec] wrote stub podspec at',
          stubPodspecPath
        );
      } catch (e) {
        console.warn('[withGoogleMapsSubspec] failed:', e);
      }
      return config;
    },
  ]);
};
