const { withDangerousMod } = require('@expo/config-plugins');
const fs = require('fs');
const path = require('path');

/**
 * react-native-maps v1.27+ no longer ships a separate
 * `react-native-google-maps` podspec. Google Maps support is now a
 * *subspec* of the main react-native-maps pod (`react-native-maps/Google`).
 *
 * Expo's built-in withMaps config plugin still injects
 *   pod 'react-native-google-maps', path: ...
 * into the Podfile whenever `ios.config.googleMapsApiKey` is set. This
 * causes EAS iOS builds to fail with:
 *   [!] No podspec found for `react-native-google-maps`
 *
 * This plugin uses TWO strategies (belt-and-suspenders):
 *   1. Writes a stub podspec to node_modules/react-native-maps/ so
 *      CocoaPods can resolve the injected pod line.
 *   2. Patches the generated Podfile to replace the broken
 *      `react-native-google-maps` pod line with `react-native-maps/Google`.
 */
module.exports = function withGoogleMapsSubspec(config) {
  return withDangerousMod(config, [
    'ios',
    async (config) => {
      const projectRoot = config.modRequest.projectRoot;

      // ── Strategy 1: stub podspec ──────────────────────────────
      try {
        const rnMapsDir = path.join(
          projectRoot,
          'node_modules',
          'react-native-maps'
        );
        if (fs.existsSync(rnMapsDir)) {
          const stubPodspecPath = path.join(
            rnMapsDir,
            'react-native-google-maps.podspec'
          );

          const stub = [
            '# Auto-generated by plugins/withGoogleMapsSubspec.js',
            "require 'json'",
            "package = JSON.parse(File.read(File.join(__dir__, 'package.json')))",
            '',
            'Pod::Spec.new do |s|',
            "  s.name         = 'react-native-google-maps'",
            "  s.version      = package['version']",
            "  s.summary      = 'Shim for react-native-maps Google subspec.'",
            "  s.homepage     = package['homepage']",
            "  s.license      = package['license']",
            "  s.authors      = package['author']",
            "  s.platform     = :ios, '16.0'",
            "  s.source       = { :path => '.' }",
            "  s.dependency 'react-native-maps/Google'",
            'end',
            '',
          ].join('\n');

          fs.writeFileSync(stubPodspecPath, stub, 'utf8');
          console.log(
            '[withGoogleMapsSubspec] ✓ wrote stub podspec at',
            stubPodspecPath
          );
        }
      } catch (e) {
        console.warn('[withGoogleMapsSubspec] stub podspec failed:', e);
      }

      // ── Strategy 2: patch Podfile ─────────────────────────────
      try {
        const podfilePath = path.join(
          config.modRequest.platformProjectRoot,
          'Podfile'
        );
        if (fs.existsSync(podfilePath)) {
          let podfile = fs.readFileSync(podfilePath, 'utf8');

          // Replace any line referencing pod 'react-native-google-maps'
          // with pod 'react-native-maps/Google' using the same path.
          const patched = podfile.replace(
            /pod\s+'react-native-google-maps'\s*,\s*path:\s*(.+)/g,
            "pod 'react-native-maps/Google', path: $1"
          );
          if (patched !== podfile) {
            fs.writeFileSync(podfilePath, patched, 'utf8');
            console.log(
              '[withGoogleMapsSubspec] ✓ patched Podfile — replaced react-native-google-maps → react-native-maps/Google'
            );
          } else {
            console.log(
              '[withGoogleMapsSubspec] Podfile does not contain react-native-google-maps line (already clean)'
            );
          }
        }
      } catch (e) {
        console.warn('[withGoogleMapsSubspec] Podfile patch failed:', e);
      }

      return config;
    },
  ]);
};
